DROP SCHEMA IF EXISTS HISTORICAL_DATA CASCADE;

CREATE SCHEMA IF NOT EXISTS HISTORICAL_DATA
    AUTHORIZATION postgres;


CREATE TABLE IF NOT EXISTS HISTORICAL_DATA.HOURLY_SERIES
(
    ID              SERIAL PRIMARY KEY,
    BEGIN_TIMESTAMP TIMESTAMP NOT NULL,
    OPEN            DECIMAL NOT NULL,
    CLOSE           DECIMAL NOT NULL,
    HIGH            DECIMAL NOT NULL,
    LOW             DECIMAL NOT NULL,
    VOLUME          INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS HOURLY_TS_IDX
    ON HISTORICAL_DATA.HOURLY_SERIES (BEGIN_TIMESTAMP);


CREATE TABLE IF NOT EXISTS HISTORICAL_DATA.THIRTY_MIN_SERIES
(
    ID              SERIAL PRIMARY KEY,
    BEGIN_TIMESTAMP TIMESTAMP NOT NULL,
    OPEN            DECIMAL NOT NULL,
    CLOSE           DECIMAL NOT NULL,
    HIGH            DECIMAL NOT NULL,
    LOW             DECIMAL NOT NULL,
    VOLUME          INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS THIRTY_MIN_TS_IDX
    ON HISTORICAL_DATA.THIRTY_MIN_SERIES (BEGIN_TIMESTAMP);

------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS HISTORICAL_DATA.FIVE_MIN_SERIES
(
    ID              SERIAL PRIMARY KEY,
    BEGIN_TIMESTAMP TIMESTAMP NOT NULL,
    OPEN            DECIMAL NOT NULL,
    CLOSE           DECIMAL NOT NULL,
    HIGH            DECIMAL NOT NULL,
    LOW             DECIMAL NOT NULL,
    VOLUME          INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS FIVE_MIN_TS_IDX
    ON HISTORICAL_DATA.FIVE_MIN_SERIES (BEGIN_TIMESTAMP);


------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS HISTORICAL_DATA.ONE_MIN_SERIES
(
    ID              SERIAL PRIMARY KEY,
    BEGIN_TIMESTAMP TIMESTAMP NOT NULL,
    OPEN            DECIMAL NOT NULL,
    CLOSE           DECIMAL NOT NULL,
    HIGH            DECIMAL NOT NULL,
    LOW             DECIMAL NOT NULL,
    VOLUME          INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS ONE_MIN_TS_IDX
    ON HISTORICAL_DATA.ONE_MIN_SERIES (BEGIN_TIMESTAMP);


------------------------------------------------------------------